### ISSUE TITLE
Analyse Sonar

### ISSUE THREAD

**Issue by legeniedesalpages** [mygreffe/maskmodel#5]
Il y a du code dupliqué entre Produit.kt et RhinoStructureDeDonneesInternesAuModule.kt (la structure evenement)
De plus il faut faire des merge request, sinon je ne peux pas commenter ton code
Lien vers l'analyse Sonar :
https://sonarcloud.io/dashboard?id=mygreffe_maskmodel

**Comment by DimLoc** [comment]
c'est réglé
